version : 2

sources:
  - name: raw
    schema : gz_raw_data
    description : the raw dataset
    tables:
      - name: raw_gz_ship
      - name : raw_gz_sales
      - name : raw_gz_product
